import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const OUT = join(process.cwd(), "convex", "voices.ts");
const raw = execFileSync("edge-tts", ["--list-voices"], { encoding: "utf8" });
const ids = raw
  .split("\n")
  .slice(2)
  .map((line) => line.trim().split(/\s+/)[0])
  .filter((id) => /^[a-z]{2,3}-/.test(id))
  .sort();

if (ids.length < 100) {
  console.error(`Only ${ids.length} voices parsed, refusing to overwrite`);
  process.exit(1);
}

const body = ids.map((id) => `  '${id}',`).join("\n");
writeFileSync(
  OUT,
  `// Generated by scripts/update-voices.mjs from \`edge-tts --list-voices\` on ${new Date().toISOString().slice(0, 10)}.\n// Regenerate with: npm run update:voices\n\nexport const EDGE_TTS_VOICES: readonly string[] = [\n${body}\n]\n`
);
console.log(`convex/voices.ts written (${ids.length} voices)`);
